language: objective-c
before_script:
  - brew update
script:
  - ./Tools/Scripts/build_and_test_travis.sh "${PWD}/Source/JavaScriptCoreCPP"
  - ./Tools/Scripts/build_and_test_travis.sh "${PWD}/Source/TitaniumKit"
